### ISSUE TITLE
Game display component size

### ISSUE THREAD

**Issue by simon987** [simon987/Much-Assembly-Required-Frontend#1]
![](https://user-images.githubusercontent.com/1919110/34392684-76022fa2-eb2c-11e7-8280-4d952301ff61.png)
The game display component is not being resized to make the site fit in the screen comfortably.  
I'm using chromium 63.0.3239.108  
OS: arch linux  
I'm not resizing the screen. i'm using full screen mode.  
My laptop is small

**Comment by simon987** [comment]
https://github.com/simon987/Much-Assembly-Required-Frontend/blob/2b96a2c77e38c695df9b6284a6bbc4904f45e216/mar/phaser/mar.js#L44-L52
I think the problem is there

**Comment by charasyn** [comment]
<img width="1266" alt="screen shot 2017-12-27 at 3 56 33 pm" src="https://user-images.githubusercontent.com/6129909/34393193-b829f4a4-eb1e-11e7-828e-04d0a23628d5.png">
This also happens on my Retina Macbook Pro running Safari 11.0.2

**Comment by leonardosnt** [comment]
That can be fixed by removing this line:
https://github.com/simon987/Much-Assembly-Required-Frontend/blob/ae375c7b080707142654d097f4ec5d60760ea849/mar/game.css#L8
or changing it to 100%
