### ISSUE TITLE
'<' in a password is striped along with any proceeding characters

### ISSUE THREAD

**Issue by Incanus-uk-zz** [simon987/Much-Assembly-Required-Frontend#17]
for example a password of '12345678<stuff' becomes '12345678'
This is because in register.re.php and auth.re.php the password is being filtered
`$password = filter_var($_POST['password'], FILTER_SANITIZE_STRING);`
As the password is never going to be displayed do we need to sanitize it?

**Comment by kevinramharak** [comment]
No, there is no reason to change the password provided by the user in any way (If there is please prove me wrong). Should be removed before it causes trouble.
