### ISSUE TITLE
Save code locally

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required-Frontend#20]
With all the server restarts and losing code. It might be a good idea to implement a feature that stores code locally. This by using the `window.localStorage` object. (also used for the text editor theme)

**Comment by SaphireLattice** [comment]
Perhaps it should load code from server **IF** there's none in the local storage? Because if it's just outdated, person can always manually press the button that pulls it from server.

**Comment by kevinramharak** [comment]
The `localStorage` code right now does:
1. nothing if `localStorage` is not available, jumps to `3`
2. set contents of editor to what is in `localStorage`, if empty jumps to `3`
3. set contents to what the server sends on login

this all happens once when the user logs in.

I guess a button to request the code from the server instead of what you have local could be usefull. That would not be that hard to implement but im waiting for @simon987 input before i add that feature

**Comment by Jaggernaut555** [comment]
The reload button already requests your code from the server, but this change to code listener will never allow it to receive as long as you have code in the local storage.

**Comment by kevinramharak** [comment]
Well thats fixed then :+1: 
 > EDIT:
Thats not fixed yet. Ill make the code i dropped happen only once at startup. Then it will stop intercepting with the client-server websocket traffic

**Comment by kevinramharak** [comment]
As with the migration to TS and quite some time passing, I don't have the time at the moment to see how to make this old patch work with the new code.

Would still like this feature to be implemented, tough from scratch would be easier imo.
