### ISSUE TITLE
Mnemonic incorrectly listed as unknown

### ISSUE THREAD

**Issue by Jaggernaut555** [simon987/Much-Assembly-Required-Frontend#22]
The mnemonics `XCHG`, `RCR`, and `RCL` are all listed as not being mnemonics even though they actually work as intended if you assemble anyway.

**Comment by Jaggernaut555** [comment]
`JO` and `JNO` do not change to the expected colour of being a mnemonic similar to the three listed above, but are not reported as errors.

**Comment by Jaggernaut555** [comment]
While we're at it, [PUSHF and POPF](https://github.com/simon987/Much-Assembly-Required/pull/83) were merged in so those need to be added too.

**Comment by simon987** [comment]
This is a temporary fix, in the future the mnemonics should be either loaded from the server or from a config file (probably a better option for compatibility with external editors)
