### ISSUE TITLE
Current console bugs out. shows incorrect value

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required-Frontend#28]
so this piece of code:
```js
                if (lines[i].length >= 40) {
                    //Split the line...
                    var subLines = lines[i].match(/.{1,40}/g);

                    for (var j = 0; j < subLines.length; j++) {

                        //Don't put a newline at the end
                        if (j !== subLines.length - 1) {
                            tmpBuffer += "\n";
                        }
                    }

                } else {
                    tmpBuffer += lines[i] + "\n";
                }
```
just filles tmpBuffer with `"\n"`'s. This becomes a problem when:
```
// this is done
myConsole.innerHTML = tmpBuffer;
```
the only way around it right now is by making sure you don't get in that if statement.
This can be done by making sure you send a `"\n"` every 40th character you send something to the comport

**Comment by SaphireLattice** [comment]
See PR #7 that should fix this as well. But haven't got merged still.

**Comment by simon987** [comment]
Should be fixed with the new console, will have to do some more testing but so far it works
