### ISSUE TITLE
Refactoring certain files

### ISSUE THREAD

**Issue by kevinramharak** [simon987/Much-Assembly-Required-Frontend#31]
So i see quite some code that could use some refactoring. For example `editor.js`:
```js
if (new RegExp('^(bp|sp)$').test(text.toLowerCase().substring(0, 2).toLowerCase())) {
    //Starts with 2-char register
    expr = text.substring(2);
}
```
1. use a 'cached' RegExp. No need to create a new RegExp object everytime you need it. Create it once then keep using it. so
```js
var regex = new RegExp('^(bp|sp)$');
if(regex.test(text)) { ... }
```
2. `text.toLowerCase().substring(0, 2).toLowerCase()` can be `text.substring(0, 2).toLowerCase()`, also if this happens in multiple statements try a code flow of `text = text.toLowerCase()` where you do all the stuff that happens on lower case after this statement.

These are just 2 examples where code can be made more readable and with less overhead. Even tough it might not be noticeable right now, no need to hit your head on it later.

Im not sure about the coding style you wan't to use tough. Since you don't have a lot of experience with JavaScript you might wan't to just pick a standardized one and go with it.

**Comment by simon987** [comment]
Ideally the whole thing should be rewritten in Typescript. The Javascript code, especially for `mar.js` needs a lot of refactoring. The whole code for th editor was written in one night so I'm not surprised to see some questionable styling problems and bugs come out.
