### ISSUE TITLE
INC/DEC instructions are not being recognized by the editor

### ISSUE THREAD

**Issue by arthurpaulino** [simon987/Much-Assembly-Required-Frontend#34]
![captura de tela de 2018-01-07 18-07-52](https://user-images.githubusercontent.com/1919110/34654126-d7b0ddbe-f3d5-11e7-9313-9d0d0c616861.png)

**Comment by ChartreuseK** [comment]
See https://github.com/simon987/Much-Assembly-Required-Frontend/pull/33
There's some front-end redesign going on at the moment, so it hasn't been updated yet. There's a few other instructions that are there but the editor doesn't know about.

**Comment by arthurpaulino** [comment]
i was too rushy

**Comment by SaphireLattice** [comment]
Perhaps in future this could be avoided by giving editor the opcode info from game itself? Like a JSON file editor loads or something like that, which contains info about mnemonics.
