### ISSUE TITLE
Feature: Compass Rose or Cardinal Direction Markers on World View

### ISSUE THREAD

**Issue by ChartreuseK** [simon987/Much-Assembly-Required-Frontend#6]
(Accidentally posted this as an issue on the backend first: https://github.com/simon987/Much-Assembly-Required/issues/86, didn't realize the front-end was in a separate repo)

I feel it would help players while writing movement code to be able to visually see on the world view the orientation of cardinal directions. The top right edge being North is not necessarily intuitive. (My initial view was that the top left edge was North).

Perhaps either some kind of Compass rose could be added to the World view to show the orientation. Alternatively the names or abbreviations of the direction could be overlaid on the arrows linking adjacent map tiles.

**Comment by simon987** [comment]
Added XY compass and direction names on hover of the arrows
